name: Deploy nuxt APP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, rpi]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Sync code
        run: |
          mkdir /var/www/tech-nuxt
          rsync -rlptDz --delete
          ./ /var/www/tech-nuxt

      - name: Rebuild container
        run: |
          cd /mnt/docker/docker-compose/nuxt/tech

          docker compose --profile tech build
          docker compose --profile tech up -d
